### ISSUE TITLE
[Week_1] baekjoon unsolved problems

### ISSUE THREAD

**Issue by hankyul2** [Algostu/boradori#1]
1주차 백준 못 푼 문제들 입니다. 

- [ ] 10172
- [ ] 1157
- [x] 1011
- [x] 2447

**Comment by SoongE** [comment]
[1011]
공간이동이 121 , 12321, 1234321 ... 순으로 점점 넓어져 가는 것은 한결님도 눈치채셨을 겁니다. 
앞으로 설명드리는 것에서 `(이동횟수, 이동거리)` 안에 있는 것은 거리의 합입니다.
자세히 보면 `121(3,4)` -> `12321(5,9)` -> `1234321(7,16)` 순으로 나열해보면 이동거리가 N^2이 될 때 이동횟수는 **2회씩** 늘어납니다. 
한 제곱수 안에는 이동거리가 2번 변하는데 (121과 12321사이에는 이동횟수가 4번, 5번이 있다) 어떠한 규칙으로 이동거리가 1 늘어나는지 찾아보세요!!
이제 입력된 값이 어떤 제곱수 안에 포함되는지 찾아보면 금방 해답을 찾을 수 있을겁니다.

**Comment by hankyul2** [comment]
감사합니다. 문제 이해하는데 많은 도움이 되었네요.

정리해보면 다음과 같은 규칙을 발견할 수 있었습니다.

￼
![image](https://user-images.githubusercontent.com/31476895/82282983-0f782200-99d0-11ea-90f7-ccc667977d52.jpeg)
