### ISSUE TITLE
[Week_1] Please Tell me the principle about chapter1-5-2 in Fundamental Data Structure

### ISSUE THREAD

**Issue by SoongE** [Algostu/boradori#2]
서칭을 통해 문제를 풀기는 했지만 왜 이렇게 코드가 작성되야 하는지 알고리즘의 원리를 잘 모르겠습니다. 😭😭
Problem)
n개의 변수 x1, ..., xn이 주어졌을 때, 이 변수들이 가질 수 있는 가능한 모든 지리 값의 조합을 구하고자 한다. 예를 들어 n=2이면 ⭕⭕,⭕❌,❌⭕,❌❌와 같은 네가지 경우가 존재한다. 이를 구하는 C++ 프로그램을 작성하여라.
작성한 기능 구현 코드는 다음과 같습니다.
```cpp
void Comb(int n)
{
    int number = pow(2, n);
    int *arr = new int[number];
    for (int i = 0; i < number; i++)
        arr[i] = i;
    for (int i = 0; i < number; i++)
    {
        for (int j = n - 1; j >= 0; j--)
        {
            int k = arr[i] >> j; //비트 연산자
            if (k & 1)
                cout << "true ";
            else
                cout << "false ";
        }
        cout << endl;
    }
}
```

`
int k=arr[i] >> j;
`
로 어떻게 문제의 기능을 구현할 수 있는지 잘 모르겠습니다. 알려주세요!

**Comment by hankyul2** [comment]
다음과 같이 n이라는 숫자가 있을때, 2진수로 출력하기 위해서는 아래 코드를 사용할 수 있습니다. 아마 아래 코드의 실행결과를 얻기위해서 @Rhcsky 님의 질문처럼 사용한 것 같습니다.

``` c
N = 34 = 0010 0020 

for(i=0;i<8;I++){
	printf(“%d”, N >> 8-I);
}
```

**Comment by SoongE** [comment]
Thank you for helping
